name: "Private Hatchways Tests"
on: [push]

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./test
      - name: Test with pytest
        run: |
          python -m pytest -s -v --junitxml="results.xml"
        working-directory: ./test
      - uses: hatchways/hatchways-action@v1
        if: always()
        with:
          api_key: ${{ secrets.HATCHWAYS_API_KEY }}
          files: |
            - test/*.xml
